services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL: postgres://miniflux:${MINIFLUX_DATABASE_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS: 1
      - CREATE_ADMIN: 1
      - ADMIN_USERNAME: admin
      - ADMIN_PASSWORD: ${MINIFLUX_ADMIN_PASSWORD}

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER: miniflux
      - POSTGRES_PASSWORD: ${MINIFLUX_DATABASE_PASSWORD}
      - POSTGRES_DB: miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

volumes:
  miniflux-db:
