server_name: "0xc84.fyi"
pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    resources:
      - compress: false
        names:
          - client
          - federation
    tls: false
    type: http
    x_forwarded: true

database:
  name: psycopg2
  args:
    user: matrix
    database: matrix
    host: matrix_db
    cp_min: 5
    cp_max: 10

registration_shared_secret_path: /run/secrets/matrix-registration-shared-secret
macaroon_secret_key_path: /run/secrets/matrix-macaroon-secret-key
form_secret_path: /run/secrets/matrix-form-secret

log_config: "/data/matrix.0xc84.fyi.log.config"
media_store_path: /data/media_store
signing_key_path: "/data/matrix.0xc84.fyi.signing.key"

report_stats: false
trusted_key_servers:
  - server_name: "matrix.org"
